### ISSUE TITLE
Geolosys Inclusion

### ISSUE THREAD

**Issue by esotericist** [gchpaco/minecraft_eso_paco#17]
This is a highly desirable mod, but it's going to require some extensive effort to incorporate.

* What dimensions should it do things in?
* What custom ores should we add?
* Is it worth the trouble of helping that dude learn how to .json?
* What do we do with bedrock ores? The reason we had bedrock ores in the first place seems at least partially filled by geolosys.

**Comment by gchpaco** [comment]
So my original thinking on this was "no ore spawning normally in the overworld, at all.  Geolosys deposits are your only source, initially.  Bedrock ores do spawn, but you need to make the machine to make them useful, so once you have mined a bunch of ore already, you can get some closer to you and more convenient."  This would require changing Bedrock Ores config to make them require the machine to work, and probably to turn coal bedrock ores on.

**Comment by gchpaco** [comment]
I'm experimenting with this.  Fortunately it's possible to do custom geolosys oregen, otherwise things could have gotten messy.

We're going to need samples for the following ores (note: SevTech does this somehow without including models through ContentTweaker, which is probably what we should do too) and they'll need ranges and the like.

- [ ] EvilCraft Dark Ore
- [ ] Thaumcraft cinnabar and amber
- [ ] VFP rock salt, natron and trona
- [ ] Forestry apatite
- [ ] Electroblob's Wizardry crystal ore (assuming we want to keep this, I haven't had time to screw with it)
- [ ] Magneticraft pyrite and wolframite (pyrite can probably re-use the gold texture)
- [ ] Thaumcraft vis crystals (may be undesirable)

An additional problem, and one I'm not sure how to resolve exactly but we might be able to by tweaking it with scripts:

- [ ] Thaumcraft adds a nether quartz ore in the overworld, that rarely drops rare earths among other things.  I don't know much about this, but geolosys assorted quartz does not appear to do the same thing.

**Comment by gchpaco** [comment]
I have something that addresses some of these and am testing it lightly.  It doesn't work for pyrite and wolframite due to an error either in Geolosys or in Magneticraft, I'm not entirely sure which.  Probably will still need those custom samples, tho; as I read it the "sample" if you don't specify one is a whole ore block.

**Comment by gchpaco** [comment]
We've managed to get this in, and it's reasonably stable (also neat).  Closing.
